### ISSUE TITLE
Using INT1 instead of INT2 with acceleroMeter.activateAutonomousMotionSwitch()

### ISSUE THREAD

**Issue by Expurrt** [winkelict/ADXL362#2]
Hello,

I was wondering if its possible to use INT1 with this function, as I already have a board wired only to INT1, and the custom detection option seems a little overkill.

The board is a wrist watch which should check if the interrupt is active and use it to signal that the user was moving in that time period.

Thank you very much.

**Comment by winkelict** [comment]
Hi,
No not possible with the library as it currently is, the function is meant as a helper function and copies the example in the datasheet. Just copy the function from the library into your own code and change the function configureInterrupt2 to 1
```
short activateAutonomousMotionSwitchINT1(uint16_t minForceInMg, uint16_t maxForceInMg, uint32_t inActminTimeInMs
												,bool linkMode, bool autoSleep, bandwidth bandwidthInHz) {
	short status=1;

	ADXL362Config config;

	config = configureSequentialMode(linkMode, bandwidthInHz,  autoSleep);
	if (config.status <= 0) return config.status;

	//wake up mode ignores min time, set to 1 sample automatically
	status = configureActivityWakeupMode(config, minForceInMg);
	if (status <= 0) return status;

        //changed to int1
	status = configureInterrupt1(ad_status_awake);
	if (status <= 0) return status;

	//this just keeps the accelerometer awake until inactivity detected for inactmintimeinms
	status = configureInActivity(config, maxForceInMg, inActminTimeInMs);
	if (status <= 0) return status;


	//when woken up, use isact/isinact to acknowledge and check what happened and call activateMode(config) again to re-enter sleep
	//in linked mode act/inact will follow each in order
	//in default mode act/inact can happen in any order
	//in loop mode no acknowledgement/interrupt clearing is necessary
	status = activateMode(config);

	return status;
}
```
ofcourse prepend the function calls with your acceleroMeter object

**Comment by Expurrt** [comment]
Thanks for the fast response!
I ended up changing the function in the library files directly because the code was dropping errors like crazy but it works now. 
I also had to change the inner part of int1 configure to "(config, ad_status_awake)" for it to work properly.
Thank you very much!

**Comment by winkelict** [comment]
Yeah was afraid of that, sorry! I should have just give you the code for custom detection that is equivalent.
Ah you're right, i added some extra checks to configure int1.
Your welcome.
Also happy to know that my library is being used!
